[package]
name = "unicode_flash_mob"
version = "2.0.6"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
embed-resource = "1.6"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
regex = "1"
anyhow = "1"
ttf-parser = "0.25"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
split-debuginfo = 'off'
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false